version: '3.1'
services:
  neo4j:
    image: neo4j:4.4-community
    restart: always
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/dataset/
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - neo4j
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_dbms_allow__upgrade=true
volumes:
  neo4jData:
    driver: local
networks:
  neo4j:
