version: 2
jobs:
    build:
      test-with-arm:
        machine: true
        resource_class: arm.medium
        steps:
          - checkout
          - run: docker-compose up -d
          - run:
              name: Waiting for Neo4J to be ready
              command: |
                for i in `seq 1 10`;
                do
                  nc -z localhost 7474 && echo Success && exit 0
                  echo -n .
                  sleep 1
                done
                echo Failed waiting for Neo4J && exit 1
      test-with-others:
        machine: true
        steps:
          - checkout
          - run: docker-compose up -d
          - run:
              name: Waiting for Neo4J to be ready
              command: |
                for i in `seq 1 10`;
                do
                  nc -z localhost 7474 && echo Success && exit 0
                  echo -n .
                  sleep 1
                done
                echo Failed waiting for Neo4J && exit 1
